import { Product } from '@/types'

// Datos mock de productos basados en los requerimientos
export const mockProducts: Product[] = [
  {
    id: '1',
    slug: 'camisetas-personalizadas',
    name: 'Camisetas personalizadas',
    description: 'Camisetas personalizadas en tallas S, M, L, XL',
    price: 35000,
    image: '/images/Camisetas.png',
    category: 'Ropa',
    featured: true,
  },
  {
    id: '2',
    slug: 'bolsas-papel-pequenas',
    name: 'Bolsas de papel pequeñas',
    description: '12 bolsas 12×19 cm',
    price: 25000,
    image: '/images/Bolsatelapeque.png',
    category: 'Bolsas',
  },
  {
    id: '3',
    slug: 'bolsas-papel-grandes',
    name: 'Bolsas de papel grandes',
    description: '12 bolsas grandes',
    price: 35000,
    image: '/images/Bolsatelagrande .png',
    category: 'Bolsas',
    featured: true,
  },
  {
    id: '4',
    slug: 'unidad-adicional-bolsas',
    name: 'Unidad adicional bolsas',
    description: 'Unidad adicional de bolsas',
    priceRange: '$3.000 – $4.000',
    price: 3500,
    image: '/images/Pines.png',
    category: 'Bolsas',
  },
  {
    id: '5',
    slug: 'hoja-pines',
    name: 'Hoja de pines',
    description: 'Hoja de pines personalizados',
    price: 6000,
    image: '/images/Pines.png',
    category: 'Accesorios',
  },
  {
    id: '6',
    slug: 'etiquetas-botellas-agua',
    name: 'Etiquetas para botellitas',
    description: '30 etiquetas 15×4 cm',
    price: 15000,
    image: '/images/etiquetasparabotellasdeagua.png',
    category: 'Etiquetas',
  },
  {
    id: '7',
    slug: 'llaveros-personalizados',
    name: 'Llaveros personalizados',
    description: 'Llaveros personalizados en diferentes formas',
    price: 3000,
    image: '/images/Llaveros.png',
    category: 'Accesorios',
  },
  {
    id: '8',
    slug: 'bolas-acrilicas-pequenas',
    name: 'Bolas acrílicas pequeñas',
    description: '7×7 cm (con o sin imágenes)',
    priceRange: '$5.000 – $6.000',
    price: 5500,
    image: '/images/Bolastradicionales .png',
    category: 'Decoración',
  },
  {
    id: '9',
    slug: 'bolas-acrilicas-grandes',
    name: 'Bolas acrílicas grandes',
    description: '10×10 cm',
    price: 7000,
    image: '/images/Bolastradicionales .png',
    category: 'Decoración',
  },
  {
    id: '10',
    slug: 'bolsas-tela-pequenas',
    name: 'Bolsas de tela pequeñas',
    description: 'Docena sin diseño / con diseño',
    priceRange: '$30.000 – $42.000',
    price: 36000,
    image: '/images/Bolsatelagrande .png',
    category: 'Bolsas',
  },
  {
    id: '11',
    slug: 'combo-fiesta-pequena',
    name: 'Combo fiesta pequeña',
    description: '12 bolsas pequeñas + pines + etiquetas',
    price: 60000,
    image: '/images/logo.png',
    category: 'Combos',
    featured: true,
  },
  {
    id: '12',
    slug: 'combo-fiesta-grande',
    name: 'Combo fiesta grande',
    description: '12 bolsas grandes + pines + etiquetas',
    price: 70000,
    image: '/images/logo.png',
    category: 'Combos',
    featured: true,
  },
  {
    id: '13',
    slug: 'kit-sorpresas',
    name: 'Kit sorpresas',
    description: 'Bolsa coloreable + rompecabezas + colores',
    price: 7000,
    image: '/images/logo.png',
    category: 'Combos',
  },
  {
    id: '14',
    slug: 'stickers',
    name: 'Stickers personalizados',
    description: 'Stickers personalizados de alta calidad',
    price: 5000,
    image: '/images/Stickers.png',
    category: 'Accesorios',
  },
]

